### ISSUE TITLE
broken backlinking 

### ISSUE THREAD

**Issue by just4mex** [zixaphir/appchan-x#912] opened 2015-05-11 07:04 UTC
74 errors occurred. [hide]
"Quote Backlinking Part 2" crashed on node Post No.9823939 (fa).
TypeError: Cannot set property 'href' of null
also involves the part 1 aswell

**Comment by zixaphir** [comment] 2015-06-05 15:41
Duplicate of #915

**Closed by zixaphir** 2015-06-05 15:41 UTC
